# This file is configured to work with localstack [Localstack.createApiGatewayService-> env=prod]
server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # Route for /auth/login to auth-service [localstack uri config]
        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/patients/** to patient-service [localstack uri config]
        - id: patient-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation #Looks for the GatewayFilterFactory prefix

        # Route for /api-docs/patients to patient-service /v3/api-docs [localstack uri config]
        - id: api-docs-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # Route for /api-docs/auth to auth-service /v3/api-docs [localstack uri config]
        - id: api-docs-auth-service
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs