spring:
  application:
    name: patient-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 4000

logging:
  level:
    root: info

# Expose all actuator endpoints over the web
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # Show details of the health report
  endpoint:
    health:
      show-details: "always"

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: admin
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  sql:
#    init:
#      mode: always