spring:
  application:
    name: patient-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 4000

logging:
  level:
    root: info

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instance:
      billingService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instance:
      billingRetry:
        maxAttempts: 2
        waitDuration: 500ms

# Expose all actuator endpoints over the web
management:
  endpoints:
    web:
      exposure:
        include: "health,info, prometheus,metrics,cache"

  # Show details of the health report
  endpoint:
    health:
      show-details: "always"
    prometheus:
      access: "unrestricted"
  prometheus:
    metrics:
      export:
        enabled: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: admin
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  sql:
#    init:
#      mode: always